# Generated by Django 4.1.1 on 2022-10-05 13:02

import core.files.storage
import core.models.mixins.vcf
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assemblies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('vcf_file', models.FileField(blank=True, max_length=2048, storage=core.files.storage.MediaStorage(), upload_to=core.models.mixins.vcf.vcf_file_path, validators=[django.core.validators.FileExtensionValidator(['vcf'])], verbose_name='VCF file')),
                ('loading', models.PositiveSmallIntegerField(choices=[(0, 'FAILURE'), (1, 'PENDING'), (2, 'STARTED'), (3, 'SUCCESS')], default=1, verbose_name='loading state')),
                ('field_type', models.CharField(choices=[('basic', 'Basic'), ('full', 'Full')], default='basic', max_length=10, verbose_name='field type')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', related_query_name='annotation', to='assemblies.assembly', verbose_name='assembly')),
            ],
            options={
                'verbose_name': 'annotation',
                'verbose_name_plural': 'annotations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnotationVEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations_vep', related_query_name='annotation_vep', to='annotations.annotation', verbose_name='annotation')),
            ],
            options={
                'verbose_name': 'annotation_vep',
                'verbose_name_plural': 'annotations_vep',
                'abstract': False,
            },
        ),
    ]
