# Generated by Django 4.1.1 on 2022-10-05 13:02

import core.files.storage
import core.models.mixins.fasta
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'assembly',
                'verbose_name_plural': 'assemblies',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasta_file', models.FileField(blank=True, max_length=2048, storage=core.files.storage.BiodbStorage(), upload_to=core.models.mixins.fasta.fasta_file_path, validators=[django.core.validators.FileExtensionValidator(['fa'])], verbose_name='FASTA file')),
                ('fasta_index_file', models.FileField(blank=True, max_length=2048, storage=core.files.storage.BiodbStorage(), upload_to=core.models.mixins.fasta.fasta_index_file_path, validators=[django.core.validators.FileExtensionValidator(['fai'])], verbose_name='FASTA index file')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('assembly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessions', related_query_name='assession', to='assemblies.assembly', verbose_name='assembly')),
            ],
            options={
                'verbose_name': 'assession',
                'verbose_name_plural': 'assessions',
                'abstract': False,
            },
        ),
    ]
